const OS_PROMPT=`SEN OMNICODE BRAIN. Oddiy o'zbekcha tushun. Production kod.`;
if(typeof AGENT_PROMPTS==='undefined'){var AGENT_PROMPTS={core_brain:OS_PROMPT,planner:'Planner',project_analyzer:'Analyzer',context_engine:'Context',tool_engine:'Tools',code_editor:'Editor. Minimal kod.',reviewer:'Reviewer',memory_engine:'Memory'};}
const AGENTS=[{i:'🧠',n:'Core Brain',d:'Qaror',k:'core_brain'},{i:'📋',n:'Planner',d:'Reja',k:'planner'},{i:'🔍',n:'Analyzer',d:'Tahlil',k:'project_analyzer'},{i:'📎',n:'Context',d:'Fayllar',k:'context_engine'},{i:'🔧',n:'Tools',d:'GitHub',k:'tool_engine'},{i:'✏️',n:'Editor',d:'Kod',k:'code_editor'},{i:'✅',n:'Reviewer',d:'Review',k:'reviewer'},{i:'💾',n:'Memory',d:'Xotira',k:'memory_engine'}];
const SELF_FILES=['index.html','app.js','agents.js','style.css'];
const MODELS={pollinations:[{v:'openai',n:'Default'},{v:'openai-large',n:'Large'},{v:'qwen-coder',n:'Qwen Coder'}],openrouter:[{v:'meta-llama/llama-3.3-70b-instruct:free',n:'Llama 70B'},{v:'deepseek/deepseek-r1:free',n:'DeepSeek R1'},{v:'qwen/qwen-2.5-72b-instruct:free',n:'Qwen 72B'}],groq:[{v:'llama-3.3-70b-versatile',n:'Llama 70B'},{v:'llama-3.1-8b-instant',n:'Llama 8B'}],custom:[{v:'default',n:'Custom'}]};
const SK='oc_vibe_v5';
let S={provider:'pollinations',apiKey:'',model:'openai',customUrl:'',ghToken:'',ghOwner:'',ghRepo:'',ghBranch:'main',maxTokens:8192,mode:'os',messages:[],files:{},curFile:null,projects:[],memory:[],stats:{req:0,tok:0},termLog:[],working:false,workSteps:[]};
function load(){try{var r=localStorage.getItem(SK);if(r)Object.assign(S,JSON.parse(r));}catch(e){}}
function save(){try{localStorage.setItem(SK,JSON.stringify(Object.assign({},S,{messages:S.messages.slice(-30),memory:S.memory.slice(-15),termLog:S.termLog.slice(-40)})));}catch(e){}}
function toast(m,t){var e=document.getElementById('toast');if(!e)return;e.textContent=m;e.className='toast show '+(t||'');setTimeout(function(){e.classList.remove('show');},2800);}
function grow(el){el.style.height='auto';el.style.height=Math.min(el.scrollHeight,110)+'px';}
function onKey(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}
function go(v){document.querySelectorAll('.view').forEach(function(x){x.classList.remove('active');});var el=document.getElementById('v-'+v);if(el)el.classList.add('active');document.querySelectorAll('.nav-btn').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-v')===v);});if(v==='agents')renderAgents();if(v==='files'||v==='explorer')renderFiles();if(v==='stats')renderStats();if(v==='set')applySet();if(v==='term')renderTerm();if(v==='projects')renderProjects();if(v==='deploy')renderDeploy();if(v==='work')renderWork();}
function setMode(m){S.mode=m;save();var a=document.getElementById('chip-fast'),b=document.getElementById('chip-os');if(a)a.classList.toggle('active',m==='fast');if(b)b.classList.toggle('active',m==='os');}
function onProv(){var pEl=document.getElementById('prov');if(!pEl)return;var p=pEl.value;var kb=document.getElementById('keyBox'),ub=document.getElementById('urlBox'),kl=document.getElementById('keyLbl');if(kb)kb.style.display=p==='pollinations'?'none':'block';if(ub)ub.style.display=p==='custom'?'block':'none';if(kl)kl.textContent=p==='openrouter'?'OpenRouter Key':p==='groq'?'Groq Key':'API Key';var sel=document.getElementById('model');if(!sel)return;sel.innerHTML='';(MODELS[p]||[]).forEach(function(m){var o=document.createElement('option');o.value=m.v;o.textContent=m.n;sel.appendChild(o);});}
function applySet(){var map={prov:S.provider,key:S.apiKey,url:S.customUrl,maxTok:String(S.maxTokens),ghToken:S.ghToken,ghOwner:S.ghOwner,ghRepo:S.ghRepo,ghBranch:S.ghBranch||'main'};Object.keys(map).forEach(function(id){var el=document.getElementById(id);if(el)el.value=map[id];});onProv();var m=document.getElementById('model');if(m)m.value=S.model;updGhStatus();}
function saveSet(){function g(id){var e=document.getElementById(id);return e?e.value.trim():'';}S.provider=g('prov')||'pollinations';S.apiKey=g('key');S.model=g('model');S.customUrl=g('url');S.maxTokens=parseInt(g('maxTok'),10)||8192;S.ghToken=g('ghToken');S.ghOwner=g('ghOwner');S.ghRepo=g('ghRepo');S.ghBranch=g('ghBranch')||'main';save();updDot();updGhStatus();toast('Saqlandi','ok');}
function updDot(){var d=document.getElementById('dot');if(d)d.className='dot'+(S.provider==='pollinations'||S.apiKey||S.customUrl?'':' off');}
function updGhStatus(){var el=document.getElementById('ghStatus');if(!el)return;if(S.ghToken&&S.ghOwner&&S.ghRepo)el.textContent='✓ '+S.ghOwner+'/'+S.ghRepo+' @'+(S.ghBranch||'main');else if(S.ghToken)el.textContent='Token bor';else el.textContent='Ulanmagan';}
function fmt(t){var h=String(t).replace(/&/g,'&').replace(/</g,'<').replace(/>/g,'>');h=h.replace(/```(\w*)\n?([\s\S]*?)```/g,function(_,l,c){return '<pre><code>'+c.trim()+'</code></pre>';});h=h.replace(/`([^`]+)`/g,'<code>$1</code>');h=h.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');h=h.replace(/\n/g,'<br>');return h;}
function renderMsgs(){var box=document.getElementById('msgs');if(!box||!S.messages.length)return;box.innerHTML='';S.messages.forEach(function(m){var d=document.createElement('div');d.className='msg '+m.role;var role=m.role==='user'?'Siz':(m.agent||'OmniCode');var badge=m.agent?'<span class="badge">'+m.agent+'</span>':'';var body=m.role==='ai'?fmt(m.content):String(m.content).replace(/</g,'<').replace(/\n/g,'<br>');d.innerHTML='<div class="msg-role">'+role+' '+badge+'</div><div class="msg-body">'+body+'</div>'+(m.meta?'<div class="msg-meta">'+m.meta+'</div>':'');box.appendChild(d);});box.scrollTop=box.scrollHeight;}
async function callAI(msgs,sysO){var sys=sysO||OS_PROMPT;var messages=[{role:'system',content:sys}].concat(msgs);var body={model:S.model,messages:messages,max_tokens:S.maxTokens,temperature:0.45};var url,headers={'Content-Type':'application/json'};if(S.provider==='pollinations')url='https://text.pollinations.ai/openai';else if(S.provider==='openrouter'){if(!S.apiKey)throw new Error('OpenRouter key kerak');url='https://openrouter.ai/api/v1/chat/completions';headers['Authorization']='Bearer '+S.apiKey;headers['HTTP-Referer']=location.origin;}else if(S.provider==='groq'){if(!S.apiKey)throw new Error('Groq key kerak');url='https://api.groq.com/openai/v1/chat/completions';headers['Authorization']='Bearer '+S.apiKey;}else if(S.provider==='custom'){if(!S.customUrl)throw new Error('URL kerak');url=S.customUrl.replace(/\/$/,'')+'/chat/completions';if(S.apiKey)headers['Authorization']='Bearer '+S.apiKey;}else throw new Error('Provayder');var res=await fetch(url,{method:'POST',headers:headers,body:JSON.stringify(body)});if(!res.ok)throw new Error('HTTP '+res.status);var data=await res.json();var content=data.choices&&data.choices[0]&&data.choices[0].message&&data.choices[0].message.content;if(!content)throw new Error('Bo‘sh javob');var tokens=(data.usage&&data.usage.total_tokens)||Math.ceil((JSON.stringify(messages)+content).length/4);S.stats.req++;S.stats.tok+=tokens;save();return{content:content,tokens:tokens};}
async function gh(path,method,body){if(!S.ghToken)throw new Error('GitHub token kerak');var res=await fetch('https://api.github.com'+path,{method:method||'GET',headers:{'Authorization':'Bearer '+S.ghToken,'Accept':'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'},body:body?JSON.stringify(body):undefined});if(!res.ok){var t=await res.text().catch(function(){return '';});throw new Error('GitHub '+res.status+': '+t.slice(0,100));}if(res.status===204)return null;return res.json();}
async function ghGetFile(path){if(!S.ghOwner||!S.ghRepo)throw new Error('Owner/Repo');var data=await gh('/repos/'+S.ghOwner+'/'+S.ghRepo+'/contents/'+path+'?ref='+encodeURIComponent(S.ghBranch||'main'));return{content:decodeURIComponent(escape(atob(data.content.replace(/\n/g,'')))),sha:data.sha,path:path};}
async function ghPutFile(path,content,message){if(!S.ghOwner||!S.ghRepo)throw new Error('Owner/Repo');var body={message:message||('OmniCode: '+path),content:btoa(unescape(encodeURIComponent(content))),branch:S.ghBranch||'main'};try{body.sha=(await ghGetFile(path)).sha;}catch(e){}return gh('/repos/'+S.ghOwner+'/'+S.ghRepo+'/contents/'+path,'PUT',body);}
async function ghLoadSelf(){toast('Yuklanmoqda...','');var loaded=[];for(var i=0;i<SELF_FILES.length;i++){try{S.files[SELF_FILES[i]]=(await ghGetFile(SELF_FILES[i])).content;loaded.push(SELF_FILES[i]);}catch(e){}}save();renderFiles();toast(loaded.length?'Yuklandi: '+loaded.join(', '):'Topilmadi',loaded.length?'ok':'err');return loaded;}
async function ghPushAll(){var names=Object.keys(S.files);if(!names.length){toast('Fayl yo‘q','err');return;}if(!confirm(names.length+' ta fayl push?'))return;toast('Push...','');try{for(var i=0;i<names.length;i++)await ghPutFile(names[i],S.files[names[i]],'OmniCode: '+names[i]);toast('Push OK','ok');termLog('✓ push');}catch(e){toast(e.message,'err');}}
async function ghListRepos(){if(!S.ghToken){toast('Token kerak','err');return;}try{var repos=await gh('/user/repos?per_page=12&sort=updated');S.messages.push({role:'ai',content:'Repos:\n'+repos.map(function(r){return '• '+r.full_name;}).join('\n'),agent:'Git'});renderMsgs();go('chat');}catch(e){toast(e.message,'err');}}
function termLog(line){S.termLog.push({t:new Date().toLocaleTimeString(),line:line});if(S.termLog.length>80)S.termLog=S.termLog.slice(-80);save();renderTerm();}
function renderTerm(){var el=document.getElementById('termOut');if(!el)return;var rows=S.termLog.length?S.termLog:[{t:'',line:'$ OmniCode terminal tayyor'}];el.innerHTML=rows.map(function(x){return '<div class="term-line"><span class="term-t">'+x.t+'</span> '+String(x.line).replace(/</g,'<')+'</div>';}).join('');el.scrollTop=el.scrollHeight;}
function termRun(){var inp=document.getElementById('termIn');if(!inp)return;var cmd=inp.value.trim();if(!cmd)return;inp.value='';termLog('$ '+cmd);if(cmd==='clear'){S.termLog=[];save();renderTerm();return;}if(cmd==='ls'){termLog(Object.keys(S.files).join(' ')||'(bo‘sh)');return;}if(cmd==='pwd'){termLog('/OmniCode');return;}if(cmd.indexOf('cat ')===0){var f=cmd.slice(4).trim();termLog(S.files[f]?S.files[f].slice(0,500):'not found');return;}termLog('(sim) '+cmd);}
function termKey(e){if(e.key==='Enter'){e.preventDefault();termRun();}}
function renderWork(){var list=document.getElementById('workSteps');if(!list)return;var steps=S.workSteps.length?S.workSteps:[{n:'Kutish',s:'idle'}];list.innerHTML=steps.map(function(s){var cls=s.s==='run'?'run':s.s==='done'?'done':'';return '<div class="work-step '+cls+'"><span class="ws-dot"></span>'+s.n+'</div>';}).join('');var brain=document.getElementById('brainAnim');if(brain)brain.classList.toggle('active',!!S.working);}
function setWork(steps){S.workSteps=steps;S.working=steps.some(function(s){return s.s==='run';});renderWork();}
function renderProjects(){var el=document.getElementById('projList');if(!el)return;if(!S.projects.length)S.projects=[{name:S.ghRepo||'Useg-kop',health:97,branch:S.ghBranch||'main',ago:'hozir'}];el.innerHTML=S.projects.map(function(p){return '<div class="proj-card"><div class="proj-name">'+p.name+'</div><div class="proj-meta">'+p.branch+' · '+p.ago+'</div><div class="proj-health">'+p.health+'% Health</div></div>';}).join('');}
function renderDeploy(){var el=document.getElementById('deployList');if(!el)return;el.innerHTML=[{n:'GitHub Pages',st:S.ghToken?'Connected':'—'},{n:'Vercel',st:'Connect'},{n:'Netlify',st:'Connect'}].map(function(d){return '<div class="deploy-row"><span>'+d.n+'</span><span class="st">'+d.st+'</span></div>';}).join('');}
function filesContext(){var keys=Object.keys(S.files);if(!keys.length)return 'Fayl yo‘q.';var s='Fayllar:\n';keys.forEach(function(k){s+='--- '+k+' ---\n'+(S.files[k]||'').slice(0,800)+'\n';});return s;}
async function runAgent(key,userMsg,agentLabel){var prompt=(AGENT_PROMPTS&&AGENT_PROMPTS[key])||OS_PROMPT;var r=await callAI([{role:'user',content:userMsg}],prompt);S.messages.push({role:'ai',content:r.content,agent:agentLabel,meta:'~'+r.tokens+' tok'});renderMsgs();return r;}
function addTip(name){var old=document.getElementById('tip');if(old)old.remove();var tip=document.createElement('div');tip.className='msg ai';tip.id='tip';tip.innerHTML='<div class="msg-role">OmniCode <span class="badge">'+name+'</span></div><div class="typing"><span></span><span></span><span></span></div>';var box=document.getElementById('msgs');if(box){box.appendChild(tip);box.scrollTop=99999;}}
async function send(){var input=document.getElementById('inp');if(!input)return;var text=input.value.trim();if(!text)return;var btn=document.getElementById('send');if(btn)btn.disabled=true;input.value='';input.style.height='auto';S.messages.push({role:'user',content:text});renderMsgs();termLog('> '+text);var tip=document.createElement('div');tip.className='msg ai';tip.id='tip';tip.innerHTML='<div class="msg-role">OmniCode</div><div class="typing"><span></span><span></span><span></span></div>';var box=document.getElementById('msgs');if(box)box.appendChild(tip);try{var low=text.toLowerCase();if(/yukla.*kod|kodimni yukla|load self/.test(low)){if(tip.parentNode)tip.remove();await ghLoadSelf();S.messages.push({role:'ai',content:'O‘z fayllar yuklandi.',agent:'Git'});}else if(/o'zing|ozing|o‘zing|self.?edit|o'zini|ozini|yangila o/.test(low)){if(tip.parentNode)tip.remove();await runSelfEdit(text);}else if(S.mode==='os'){await runOS(text);}else{var hist=S.messages.filter(function(m){return m.role==='user'||m.role==='ai';}).slice(-10).map(function(m){return{role:m.role==='ai'?'assistant':'user',content:m.content};});var r=await callAI(hist);S.messages.push({role:'ai',content:r.content,meta:S.provider+' · ~'+r.tokens+' tok'});}}catch(e){S.messages.push({role:'ai',content:'❌ '+e.message});termLog('✗ '+e.message);}var t2=document.getElementById('tip');if(t2)t2.remove();renderMsgs();if(btn)btn.disabled=false;input.focus();renderStats();setWork([{n:'Tayyor',s:'done'}]);S.working=false;renderWork();}
async function runOS(task){go('work');var pipe=document.getElementById('pipe');if(pipe)pipe.classList.add('show');var ids=['ps1','ps2','ps3','ps4','ps5'];ids.forEach(function(id){var e=document.getElementById(id);if(e)e.className='ps';});function step(i,st){var e=document.getElementById(ids[i]);if(e)e.className='ps '+st;}var ctx=filesContext();setWork([{n:'Tushunish',s:'run'},{n:'Reja',s:'idle'},{n:'Kod',s:'idle'},{n:'Review',s:'idle'}]);step(0,'run');var t=document.getElementById('tip');if(t)t.remove();addTip('Core Brain');var brain=await runAgent('core_brain','Vazifa:\n'+task+'\n\n'+ctx,'Core Brain');step(0,'done');setWork([{n:'Tushunish',s:'done'},{n:'Reja',s:'run'},{n:'Kod',s:'idle'},{n:'Review',s:'idle'}]);step(1,'run');addTip('Planner');var plan=await runAgent('planner','Vazifa: '+task+'\n'+brain.content,'Planner');step(1,'done');setWork([{n:'Tushunish',s:'done'},{n:'Reja',s:'done'},{n:'Kod',s:'run'},{n:'Review',s:'idle'}]);step(2,'run');addTip('Editor');var code=await runAgent('code_editor','Vazifa: '+task+'\nReja:\n'+plan.content+'\n\n'+ctx+'\n\nKod:\n```til\n// filename: nom.ext\nkod\n```','Editor');extractFiles(code.content);step(2,'done');setWork([{n:'Tushunish',s:'done'},{n:'Reja',s:'done'},{n:'Kod',s:'done'},{n:'Review',s:'run'}]);step(3,'run');step(4,'run');addTip('Reviewer');await runAgent('reviewer','Review:\n'+code.content.slice(0,3500),'Reviewer');step(3,'done');step(4,'done');setWork([{n:'Tushunish',s:'done'},{n:'Reja',s:'done'},{n:'Kod',s:'done'},{n:'Review',s:'done'}]);termLog('✓ Agent OS');go('chat');}
async function runSelfEdit(task){if(!S.ghToken||!S.ghOwner||!S.ghRepo)throw new Error('GitHub sozlang');go('work');setWork([{n:'Self-Load',s:'run'},{n:'Edit',s:'idle'},{n:'Push',s:'idle'}]);addTip('Self-Load');await ghLoadSelf();setWork([{n:'Self-Load',s:'done'},{n:'Edit',s:'run'},{n:'Push',s:'idle'}]);var ctx=SELF_FILES.filter(function(f){return S.files[f];}).map(function(f){return '=== '+f+' ===\n'+(S.files[f]||'').slice(0,2500);}).join('\n\n');addTip('Editor');var code=await runAgent('code_editor','Self-edit: '+task+'\n\n'+ctx+'\n\n```js\n// filename: app.js\n...\n```','Editor');extractFiles(code.content);setWork([{n:'Self-Load',s:'done'},{n:'Edit',s:'done'},{n:'Push',s:'run'}]);if(confirm('Push qilaymi?')){var changed=Object.keys(S.files).filter(function(f){return SELF_FILES.indexOf(f)>=0;});for(var i=0;i<changed.length;i++){try{await ghPutFile(changed[i],S.files[changed[i]],'self-edit');}catch(e){S.messages.push({role:'ai',content:'❌ '+e.message,agent:'Git'});}}toast('Push OK','ok');S.messages.push({role:'ai',content:'✅ Yangilandi. Refresh.',agent:'Git'});}setWork([{n:'Self-Load',s:'done'},{n:'Edit',s:'done'},{n:'Push',s:'done'}]);go('chat');}
function extractFiles(text){var re=/```(\w*)\n(?:\/\/\s*filename:\s*([^\n]+)\n)?([\s\S]*?)```/g;var m,c=0;while((m=re.exec(text))!==null){var name=m[2]?m[2].trim():null;var code=m[3].trim();if(!name){var map={html:'html',css:'css',javascript:'js',js:'js',python:'py',ts:'ts',json:'json'};name='file'+(++c)+'.'+(map[m[1]]||'txt');}else c++;S.files[name]=code;}if(c){save();renderFiles();toast(c+' ta fayl','ok');}}
function renderAgents(){var el=document.getElementById('agentList');if(!el)return;el.innerHTML=AGENTS.map(function(a){return '<div class="agent-row"><span class="ico">'+a.i+'</span><div class="info"><div class="nm">'+a.n+'</div><div class="ds">'+a.d+'</div></div><span class="st">Tayyor</span></div>';}).join('');}
function renderFiles(){var list=document.getElementById('fileList');if(!list)return;var names=Object.keys(S.files);if(!names.length){list.innerHTML='<div style="padding:12px;color:var(--text3);font-size:13px">Fayl yo‘q</div>';return;}list.innerHTML=names.map(function(n){return '<div class="file-row '+(S.curFile===n?'active':'')+'" onclick="openFile(\''+n.replace(/'/g,"\\'")+'\')"><span>📄</span><span class="n">'+n+'</span></div>';}).join('');var list2=document.getElementById('explorerList');if(list2)list2.innerHTML=list.innerHTML;}
function newFile(){var n=prompt('Fayl nomi:');if(!n||!n.trim())return;n=n.trim();if(S.files[n]){toast('Bor','err');return;}S.files[n]='';S.curFile=n;var en=document.getElementById('edName'),ed=document.getElementById('ed');if(en)en.textContent=n;if(ed)ed.value='';save();renderFiles();go('files');toast('OK','ok');}
function openFile(n){var ed=document.getElementById('ed');if(S.curFile&&ed)S.files[S.curFile]=ed.value;S.curFile=n;var en=document.getElementById('edName');if(en)en.textContent=n;if(ed)ed.value=S.files[n]||'';renderFiles();go('files');}
function saveFile(){if(!S.curFile){toast('Fayl tanlang','err');return;}var ed=document.getElementById('ed');if(ed)S.files[S.curFile]=ed.value;save();toast('Saqlandi','ok');}
function dlFile(){if(!S.curFile)return;var ed=document.getElementById('ed');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([(ed&&ed.value)||''],{type:'text/plain'}));a.download=S.curFile;a.click();}
function delFile(){if(!S.curFile||!confirm('O‘chirish?'))return;delete S.files[S.curFile];S.curFile=null;var en=document.getElementById('edName'),ed=document.getElementById('ed');if(en)en.textContent='—';if(ed)ed.value='';save();renderFiles();toast('OK','ok');}
function renderStats(){var a=document.getElementById('sReq'),b=document.getElementById('sTok'),c=document.getElementById('sFil'),d=document.getElementById('sPrj');if(a)a.textContent=S.stats.req;if(b)b.textContent=S.stats.tok.toLocaleString();if(c)c.textContent=Object.keys(S.files).length;if(d)d.textContent=(S.projects&&S.projects.length)||0;}
function clearChat(){if(!confirm('Tozalash?'))return;S.messages=[];save();var box=document.getElementById('msgs');if(box)box.innerHTML='<div class="msg ai"><div class="msg-role">OmniCode</div><div class="msg-body">Chat tozalandi.</div></div>';toast('OK','ok');}
function wipe(){if(!confirm('Hammasi?'))return;localStorage.removeItem(SK);location.reload();}
window.go=go;window.setMode=setMode;window.onProv=onProv;window.saveSet=saveSet;window.send=send;window.onKey=onKey;window.grow=grow;window.clearChat=clearChat;window.wipe=wipe;window.newFile=newFile;window.openFile=openFile;window.saveFile=saveFile;window.dlFile=dlFile;window.delFile=delFile;window.ghPushAll=ghPushAll;window.ghLoadSelf=ghLoadSelf;window.ghListRepos=ghListRepos;window.termRun=termRun;window.termKey=termKey;
load();updDot();renderMsgs();renderFiles();renderTerm();renderProjects();renderDeploy();renderWork();
